# This file was generated by GoReleaser. DO NOT EDIT.
cask "heybox" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "616cc2b4d00e6e3f1b370b5ef003ebc62df71e1755b760e04b8a22761639d8a5"
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v#{version}/heybox_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/shadowfish07/heybox-cli/"
    end
    on_arm do
      sha256 "a47511b72594abd0ac103f5222219960f6ee9ce372ff1b2c3fd24b95e9633252"
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v#{version}/heybox_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/shadowfish07/heybox-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "002b96bdf9f0a2975fbf72cf2c104bba588eb8c2ea5d148fb05d18eb8633b1cc"
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v#{version}/heybox_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/shadowfish07/heybox-cli/"
    end
    on_arm do
      sha256 "46ce4b89a74c8a897330207b2e0292434cf028e5385ed1bf89d058a72a30d717"
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v#{version}/heybox_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/shadowfish07/heybox-cli/"
    end
  end

  name "heybox"
  desc "Read-only CLI for searching the Heybox community"
  homepage "https://github.com/shadowfish07/heybox-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heybox"

  generate_completions_from_executable "heybox",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
