# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heybox < Formula
  desc "Read-only CLI for searching the Heybox community"
  homepage "https://github.com/shadowfish07/heybox-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.3.0/heybox_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "ca4f49b7a52d53b23c7256aa50e7cc00e4e1eae6dbd440b2ef4d5571dcba1d3c"

      define_method(:install) do
        bin.install "heybox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.3.0/heybox_0.3.0_Darwin_arm64.tar.gz"
      sha256 "e5e5be2c63bea13ba52e5120cc96b3e6f4b40f6d52ecc7a7e3a31b25eb4b939b"

      define_method(:install) do
        bin.install "heybox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.3.0/heybox_0.3.0_Linux_x86_64.tar.gz"
      sha256 "6d897d669db947528abb84380e519a9299ef3bf6c6da44d8917e65cc68132a4b"
      define_method(:install) do
        bin.install "heybox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.3.0/heybox_0.3.0_Linux_arm64.tar.gz"
      sha256 "b2af813e43302ecf1f3f944f1fde8568d80a8f8cfdaa3d3211a5626f05a362a8"
      define_method(:install) do
        bin.install "heybox"
      end
    end
  end

  test do
    system "#{bin}/heybox", "--version"
  end
end
