# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heybox < Formula
  desc "Read-only CLI for searching the Heybox community"
  homepage "https://github.com/shadowfish07/heybox-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.2.0/heybox_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "e6a936066a1df673a64fe83f86b7793fedfbaf1cac06f3f2ef33ce55465d57d6"

      define_method(:install) do
        bin.install "heybox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.2.0/heybox_0.2.0_Darwin_arm64.tar.gz"
      sha256 "1c59719f254c5240c7741a3dba9b3cb05e12ebfb4732c93f56595c8a15895687"

      define_method(:install) do
        bin.install "heybox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.2.0/heybox_0.2.0_Linux_x86_64.tar.gz"
      sha256 "dee1e4c2d8e82c5b144883f66b8a1d3ece09eef7affe88223e3739d73bbbe822"
      define_method(:install) do
        bin.install "heybox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.2.0/heybox_0.2.0_Linux_arm64.tar.gz"
      sha256 "e9b7f6c7c086df935b0721c047e0ad4c2ea71cc9c35c3a1a25f79afe8377fd9f"
      define_method(:install) do
        bin.install "heybox"
      end
    end
  end

  test do
    system "#{bin}/heybox", "--version"
  end
end
