# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heybox < Formula
  desc "Read-only CLI for searching the Heybox community"
  homepage "https://github.com/shadowfish07/heybox-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.1.2/heybox_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "3932112c207f3e122004d6169cf51215445d8a0fe219b75986b665f851c1b340"

      define_method(:install) do
        bin.install "heybox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.1.2/heybox_0.1.2_Darwin_arm64.tar.gz"
      sha256 "acadb9a4fb0a8be5d83d7421cbb07d75810bb11e4d826cf4f2189639351485d6"

      define_method(:install) do
        bin.install "heybox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.1.2/heybox_0.1.2_Linux_x86_64.tar.gz"
      sha256 "040730fd20e54e72a05e45e2b29033849876d463ae3e98201e0740f65d71e4d1"
      define_method(:install) do
        bin.install "heybox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadowfish07/heybox-cli/releases/download/v0.1.2/heybox_0.1.2_Linux_arm64.tar.gz"
      sha256 "6c3f6c13085b82688c15495ec811f29f15756bda62dca32c8a3b07c0009bbe99"
      define_method(:install) do
        bin.install "heybox"
      end
    end
  end

  test do
    system "#{bin}/heybox", "--version"
  end
end
